server.port: 8083

spring:
  cloud:
    gateway:
      routes:
      # =====================================
      - id: security_route
        uri: http://localhost:8083/index.html
        predicates:
        - Path=/{segment}-view/**
        filters:
        - RewritePath=/(?<segment>.*)-view, /